BINANCE_BASE_ENDPOINT = "BINANCE_BASE_ENDPOINT"
BINANCE_EXCHANGE_INFORMATION_API = "/api/v3/exchangeInfo"
BINANCE_BOOK_TICKER_API = "/api/v3/ticker/bookTicker"
TRIANGULAR_PAIRS_SAVE_FILE_PATH = "triangular-pairs.json"